version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    # run first time.
    # command: mkdir code; cd code; django-admin startproject testproject .
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true

volumes:
  postgres_data: